### ISSUE TITLE
[2.0] Settings not saved

### ISSUE THREAD

**Issue by Nokius** [modulebaan/harbour-sailfinder#44] opened 2016-09-02 16:15 UTC
It may related to the issue #43

Settings for range and age are after enabling of the Discovery set to default

**Comment by modulebaan** [comment] 2016-09-02 20:24
Likely it's related

**Comment by modulebaan** [comment] 2016-09-07 11:07
Added workaround in V2.1-1 since nobody replies here, I can't test it for 100% certainty because I can't reproduce this issue

**Comment by modulebaan** [comment] 2016-09-13 13:30
Error still present

**Comment by modulebaan** [comment] 2016-09-13 14:43
Thanks to Lauri from the Jolla QA I had a testaccount with this issue and it's fixed in V2.2-1

**Closed by modulebaan** 2016-09-13 14:43 UTC
Labels: 3rd party related
