### ISSUE TITLE
[3.0] Match pop-up visible after acknowledge

### ISSUE THREAD

**Issue by Nokius** [modulebaan/harbour-sailfinder#101] opened 2017-03-23 17:34 UTC
By accident I discovered that the match pop-up is visible when the user turns the device.

See attached [screenshot](https://cloud.githubusercontent.com/assets/879178/24261431/3be7f164-0ff7-11e7-8346-d30c527715c6.png)

**Comment by modulebaan** [comment] 2017-03-29 14:50
I want to reproduce it but I can't, can you describe the exact circumstances?

**Comment by Nokius** [comment] 2017-03-29 15:13
Well I can try  my best :)

After a match the pop-up showed up, which I pressed and it faded away.
Then I rotated the Device and the pop-up was visible again as you can see in the screenshot.

**Comment by modulebaan** [comment] 2017-03-29 15:24
Oh when you have match and clicked it away, that's interesting... Maybe I can figure this out for the next version or a later version.

**Comment by Nokius** [comment] 2017-03-29 15:27
Sure, I will try to see how the pop-up looks like in landscape mode. Let's hope there is soon one :s

**Comment by modulebaan** [comment] 2017-04-08 12:07
Reproduced it and tried to fix it in V3.1, however I couldn't test the fix completely yet.

**Comment by Nokius** [comment] 2017-04-11 00:44
=) I will test it too let's hope soon there is a match Thanks for 3.1

**Comment by modulebaan** [comment] 2017-04-11 08:02
I tried it but it's seems that this issue is still there... Will try to find how to fix this but this is more a problem with the DockedPanel itself and not with my QML code. Since I request to close the panel but it appears while turning the device... Maybe I will replace the panel completely by my own version of it.

**Comment by Nokius** [comment] 2017-04-13 07:10
I was not able to reproduce it with 3.1

**Comment by modulebaan** [comment] 2017-04-13 11:33
Well I guess then it's OK to close this one again 👍

**Closed by modulebaan** 2017-04-13 11:33 UTC
Labels: bug
