### ISSUE TITLE
Message clipped

### ISSUE THREAD

**Issue by Sikarjan** [modulebaan/harbour-sailfinder#209] opened 2019-08-11 20:28 UTC
1. **What happens**: 
    - In some cases, I believe when there is only one word in the last line, the last word is not displayed. There is enough room between the last line and the date but it is empty.
    
2. **What was expected**:
    - Message is not displayed completely.

3. **How to reproduce**: 
    1. Send or receive a message

4. **Environment**: 
    - Sailfish OS version: 3.1.0.11
    - Sailfish OS hardware: Jolla C

**Comment by DylanVanAssche** [comment] 2019-08-13 09:23
Thanks for the report.
This is a known issue, unfortunately, there's no fix available for it.
Duplicate of #201

**Closed as completed by DylanVanAssche** 2019-08-13 09:23 UTC
