### ISSUE TITLE
2.0.4.14 During Like I am Getting Error

### ISSUE THREAD

**Issue by CaptainKhan** [modulebaan/harbour-sailfinder#73] opened 2016-11-21 06:47 UTC
pyotherside.send() failed handler: file:///usr/share/harbour-sailfinder/qml/pages/MainPage.qml:929: Error: Cannot assign [undefined] to bool

For dislike it goes to the next person as it should. Otherwise i can login change profile images etc with no problem. I also tried to login and logout a couple times with repeat error.

**Comment by modulebaan** [comment] 2016-11-21 08:09
Unfortunately I can't repeat this issue with my accounts... I will take a look at the source code where this issue arises

**Comment by CaptainKhan** [comment] 2016-11-21 08:22
thanks for checking on it, with those errors i have to close the app and on relaunching when trying to update my profile it usually says login expired login again even though its already authorized and was just logged in a session before, FYI.

**Comment by modulebaan** [comment] 2016-11-21 15:24
Does it works after that?

**Comment by CaptainKhan** [comment] 2016-11-21 16:04
No it doesnt work still. I tried setting changes in the profile all private, all public still the same. I tried mobile data, wifi, and with secure fishnet on and off, same.
The generate share link also just spins and shows its loading something but it doesnt work. Otherwise the location, images, loading the persons photos, instagram, bio, job, and school work.

**Comment by CaptainKhan** [comment] 2016-11-21 21:53
Here is the more complete log:

Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)

  File "<string>", line 2, in raise_from

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()

  File "/usr/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()

  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()

  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)

http.client.BadStatusLine: ''


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/adapters.py", line 423, in send
    timeout=timeout

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/util/retry.py", line 261, in increment
    raise six.reraise(type(error), error, _stacktrace)

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)

  File "<string>", line 2, in raise_from

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()

  File "/usr/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()

  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()

  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)

lib.requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/share/harbour-sailfinder/qml/pages/api.py", line 257, in update_location
    location = postTinder('/user/ping', data)

  File "/usr/share/harbour-sailfinder/qml/pages/api.py", line 28, in postTinder
    result = session.post(constants.TINDER_HOST + url, data=data)

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)

lib.requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by CaptainKhan** [comment] 2016-11-21 23:48
Ok i found the solution after reading about other people having similar issues with the app. I installed dbus libraries from open repos and now it works:

this one i believe (i ended up installing a bunch of dbus related apps)

https://openrepos.net/content/coderus/nemo-qml-plugin-dbusnext-qt5

**Comment by modulebaan** [comment] 2016-11-22 09:44
Normally Sailfinder doesn't use DBUS but from what I see in the error that it's related to location pinging.

In V2.4 I added a connection checker which also will handle this issue I think

**Comment by CaptainKhan** [comment] 2016-11-22 16:59
i see, it seems to work periodically but creates error when left open over time:

Return value of PyObject call is NULL: Traceback (most recent call last):

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)

  File "<string>", line 2, in raise_from

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()

  File "/usr/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()

  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()

  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)

http.client.BadStatusLine: ''


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/adapters.py", line 423, in send
    timeout=timeout

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/util/retry.py", line 261, in increment
    raise six.reraise(type(error), error, _stacktrace)

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)

  File "<string>", line 2, in raise_from

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/packages/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()

  File "/usr/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()

  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()

  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)

lib.requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/share/harbour-sailfinder/qml/pages/api.py", line 257, in update_location
    location = postTinder('/user/ping', data)

  File "/usr/share/harbour-sailfinder/qml/pages/api.py", line 28, in postTinder
    result = session.post(constants.TINDER_HOST + url, data=data)

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)

  File "/usr/share/harbour-sailfinder/qml/pages/lib/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)

lib.requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by modulebaan** [comment] 2016-11-23 05:30
That's a known issue since it periodically updates your location and if your connection is then not available Sailfinder crashes. 

I will give you the development RPM of the upcoming version and then you can see if the issue is gone?

**Comment by CaptainKhan** [comment] 2016-11-23 05:43
yes please that would be great: then-there-we-go@my.com

ill test it, also i notice it crashes and doesnt recover upon mobile, or wifi disconnect from network. if you want i can send you those logs too

**Comment by CaptainKhan** [comment] 2016-11-23 05:44
Once i have charged up my flatr account ill send you some support :) for the hard work.

**Comment by modulebaan** [comment] 2016-11-24 10:43
Fixed in V2.4

**Closed by modulebaan** 2016-11-24 10:43 UTC
