### ISSUE TITLE
[2.0+2.1] Discovery is disabled 

### ISSUE THREAD

**Issue by Nokius** [modulebaan/harbour-sailfinder#43] opened 2016-09-02 16:11 UTC
During browsing the new "Update Profile" page I saw that the Discovery was disabled 

I set it on (clicking on it)  after reopening it was again set to off

**Comment by modulebaan** [comment] 2016-09-02 20:23
I can't reproduce it, I will check it in the code again

**Comment by modulebaan** [comment] 2016-09-03 06:39
I checked it but it's related to your account I guess since it works fine here with 2 accounts and my beta tester also doesn't encountered this issue.

Have you tried it with the official Tinder app?

**Comment by debexpert** [comment] 2016-09-03 09:37
Hey Nokius, must be a problem of yours only, we are not able to reprodce, I am discoverable and notice that the feature it is working well on all the beta versions

**Comment by debexpert** [comment] 2016-09-03 13:29
Hey modulebaan if there is a bug, as I see u add the tag, it is on Tinder side and on some other accounts . We are not able to reproduce this one and won't accept it as a bug on Sailfinder, because it is not related to the app itslelf

**Comment by debexpert** [comment] 2016-09-03 13:32
Nokius plz confirm whether you are on Aurajoki (early update) or on stable Saimaa. I am on stable even if early adopter, because a bit part of the global users are on stable v.

**Comment by modulebaan** [comment] 2016-09-04 06:26
More then one user is affected -> bug

**Comment by modulebaan** [comment] 2016-09-04 06:30
@Nokius 
The problem is that I can't reproduce it with my accounts. 
Do you have experience with the Sailfish SDK? Maybe you can help debugging ... 
Another possibility is that I log into your account and check it myself but I understand that you can't give your credentials to a stranger on the internet

**Comment by modulebaan** [comment] 2016-09-04 06:38
I found one case when that could happen:
1. Change discovery (or other stuff)
2. Upload picture
3. Go back to 'Update Profile'
4. Discovery (and other stuff) are not saved except the picture

**Comment by modulebaan** [comment] 2016-09-07 11:07
Added workaround in V2.1-1 since nobody replies here, I can't test it for 100% certainty because I can't reproduce this issue

**Comment by modulebaan** [comment] 2016-09-08 06:41
Issue still present in V2.1-1
For an unknown reason some accounts won't receive the same JSON string then all the rest.
Someone from the store has discovered the error in the Journal but I need more information (the actual JSON string) to fix it.

**Comment by modulebaan** [comment] 2016-09-13 14:43
Thanks to Lauri from the Jolla QA I had a testaccount with this issue and it's fixed in V2.2-1

**Closed by modulebaan** 2016-09-13 14:43 UTC
Labels: 3rd party related, bug, wait for something

**Comment by Nokius** [comment] 2016-09-14 12:42
I'm sorry, the last days I was not able to go online.

**Comment by modulebaan** [comment] 2016-09-15 09:04
No problem @Nokius :)

**Comment by debexpert** [comment] 2016-10-23 17:07
Anyway we are already on 2.3 beta, we dont have the issue there, I repeat, me and dev could not reproduce the issue on any version

**Comment by debexpert** [comment] 2016-10-23 17:09
@modulebaan ok you have a dev vision of what is bug, me tester and I'd call it defect :) thx for the fixes

**Comment by Nokius** [comment] 2016-10-23 17:09
I don't use this service anymore sorry can't help

**Comment by debexpert** [comment] 2016-10-23 17:10
ok @Nokius no problem anyway @modulebaan made the fixes! thx to him!

**Comment by Nokius** [comment] 2016-10-23 17:16
yep modulebaan did a great job
